// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5665.RacknRoll2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveRight;
    public static SpeedController driveLeft;
    public static RobotDrive driveRobotDrive2;
    public static Encoder armEncoderRight;
    public static SpeedController armMotorRight;
    public static Encoder armEncoderLeft;
    public static SpeedController armMotorLeft;
    public static Relay platformLock;
    public static Encoder platformEncoderRight;
    public static SpeedController platformMotorRight;
    public static Encoder platformEncoderLeft;
    public static SpeedController platformMotorLeft;
    public static SpeedController wristWindowMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveRight = new Victor(0);
        LiveWindow.addActuator("Drive", "Right", (Victor) driveRight);
        
        driveLeft = new Victor(1);
        LiveWindow.addActuator("Drive", "Left", (Victor) driveLeft);
        
        driveRobotDrive2 = new RobotDrive(driveLeft, driveRight);
        
        driveRobotDrive2.setSafetyEnabled(true);
        driveRobotDrive2.setExpiration(0.1);
        driveRobotDrive2.setSensitivity(0.5);
        driveRobotDrive2.setMaxOutput(1.0);

        driveRobotDrive2.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        armEncoderRight = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("Arm", "Encoder Right", armEncoderRight);
        armEncoderRight.setDistancePerPulse(0.724346);
        armEncoderRight.setPIDSourceType(PIDSourceType.kRate);
        armMotorRight = new Talon(2);
        LiveWindow.addActuator("Arm", "Motor Right", (Talon) armMotorRight);
        
        armEncoderLeft = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("Arm", "Encoder Left", armEncoderLeft);
        armEncoderLeft.setDistancePerPulse(1.0);
        armEncoderLeft.setPIDSourceType(PIDSourceType.kRate);
        armMotorLeft = new Victor(6);
        LiveWindow.addActuator("Arm", "Motor Left", (Victor) armMotorLeft);
        
        platformLock = new Relay(0);
        LiveWindow.addActuator("Platform", "Lock", platformLock);
        
        platformEncoderRight = new Encoder(6, 7, false, EncodingType.k4X);
        LiveWindow.addSensor("Platform", "Encoder Right", platformEncoderRight);
        platformEncoderRight.setDistancePerPulse(1.0);
        platformEncoderRight.setPIDSourceType(PIDSourceType.kRate);
        platformMotorRight = new Talon(5);
        LiveWindow.addActuator("Platform", "Motor Right", (Talon) platformMotorRight);
        
        platformEncoderLeft = new Encoder(4, 5, false, EncodingType.k4X);
        LiveWindow.addSensor("Platform", "Encoder Left", platformEncoderLeft);
        platformEncoderLeft.setDistancePerPulse(1.0);
        platformEncoderLeft.setPIDSourceType(PIDSourceType.kRate);
        platformMotorLeft = new Talon(3);
        LiveWindow.addActuator("Platform", "Motor Left", (Talon) platformMotorLeft);
        
        wristWindowMotor = new Victor(4);
        LiveWindow.addActuator("Wrist", "Window Motor", (Victor) wristWindowMotor);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
